# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 59d420336a95edc282e20bc38cbbe508acb434e1f483cac505f762c086121420db4cea0ca5d8e04515f44ed02e25862291a785d80177452b132994d9a8aed87c

test:
  secret_key_base: 9b777bd9f68d71edac74662b830f4fccaaad00ee44b05ab54c7d501c43d6e5bfe0651e99974cf30e2fa6971f123b8cd3a8e8f42140e0cc24c3d92df72d219cc4
  bitly_username: o_7u9h2qju48
  bitly_token: R_666f58d2732e4b309ce3f6c0932469e2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
